### ISSUE TITLE
click on "<-" stop recording

### ISSUE THREAD

**Issue by PH64** [ekylibre/zero-android#13]
When you click on button return on the top of intervention's screen, it stops the recording.

**Comment by PierreBougon** [comment]
It's the normal behavior of an android app. In the next release I will make this behavior more explicit.
Do you need to do something else on the app during your intervention ?

**Comment by PH64** [comment]
It should be practice to enter an issue during the intervention

**Comment by PierreBougon** [comment]
Link with #27

**Comment by PierreBougon** [comment]
New enhancement of back buttons. Issue is fix.
