### ISSUE TITLE
Guide of development

### ISSUE THREAD

**Issue by djKooks** [ekylibre/zero-android#31]
Hello~nice to see you.
I am interest on your project, and hope to get involved if it is possible.

Is there some kind of guide or process to use this application?
I success on loading app from source, but cannot login.

Thanks.

**Comment by PierreBougon** [comment]
Hello,

This application is dependent on [Ekylibre](https://ekylibre.com/).
You can find more informations on how to use it from [Wiki](https://wiki.ekylibre.org/en/start) but it is essentially written in french.
