### ISSUE TITLE
When i've terminated an intervention, the state are in progress in Ekylibre (Maybe on API side)

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/zero-android#33]
In case of, i'am alone in the intervention request and i ve saved my intervention on zero.
When i sign-in to Ekylibre, my intervention has still the state 'in progress'

**Comment by Aquaj** [comment]
Opening on Ekylibre @ ekylibre/ekylibre#1258.

**Comment by Aquaj** [comment]
Should be closed on Ekylibre. I can't close the issue here though so I leave it to you, @ionosphere.
