### ISSUE TITLE
Contact are not syncronising on the phone

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/zero-android#36]
Error message
from [Cedric Lambert]
None, just no contact sync

SAMSUNG X cover 3
Android 6.0.1
App version https://github.com/ekylibre/zero-android/releases/tag/v0.7.4

1- How to reproduce?

Install application on Android 6.0.1 and connect to one instance with url, login and password.

2- What is really expected?

See a contact on each side (Web app and phone)

3- How to test it?

Install application on Android 6.0.1 and connect to one instance with url, login and password.
Check sync contact option on app.

**Comment by PierreBougon** [comment]
If I remember well, the phone to WebApp side is not implemented yet. The other side should work.

**Comment by burisu** [comment]
If  the mono-directional sync work, we can chang e message to explicit the direction of sync.
