### ISSUE TITLE
Issues pictures take with zero don't go back in Ekylibre

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/zero-android#39]
**Description**

When a user create an issue with a picture on the app, the issue is created on the server side but we can't retrieve the picture.

**How to reproduce**

1 * Install the mobile app on your Android phone, use the demo credentials on https://demo.ekylibre.farm (admin@ekylibre.org / 12345678)
2 * Create an issue.
3 * Clic on syncing the app
4 * Go to https://demo.ekylibre.farm/backend/issues and see that we have the issue without the picture(s)

**What is expected**

Having the issue with pictures when we take it from the mobile app.

**Comment by burisu** [comment]
We'll disable images until API is ready.
