### ISSUE TITLE
 Crops killed in Ekylibre are sent in Zero plant countings

### ISSUE THREAD

**Issue by PH64** [ekylibre/zero-android#41]
Crops killed in Ekylibre are sent in Zero plant countings

Even if plants have a dead date in Ekylibre, dead plants are are in Zero plant counting
https://github.com/ekylibre/ekylibre/issues/1556

**Comment by linuxipho** [comment]
Not reproducible. Crops that have been killed in Ekylibre are not displayed by Zero in plant counting.
