### ISSUE TITLE
A deleted provisionnal intervention on Ekylibre remain on Zero after synchronisation.

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/zero-android#44]
**Description**

When a user has created a provisionnal intervention on Ekylibre and then the concerned user has sync the data on Zero app. the user see the provisionnal intervention on his app.

But if a user deleted the provisionnal intervention on Ekylibre and then the concerned user re-sync the app, the provisionnal intervention remains on the app.

**How to reproduce**

1 * Install the mobile app on your Android phone, use the demo credentials on https://demo.ekylibre.farm (admin@ekylibre.org / 12345678)
2 * Connect on https://demo.ekylibre.farm and create a provisionnal intervention on https://demo.ekylibre.farm/backend/interventions/new?nature=request and then select a sprayin intervention an assign the user CD Christian DUPONT (P00000000121).
3 * Then return on the mobile app and clic on sync.
4 * Return on https://demo.ekylibre.farm/backend/interventions and delete the concerning intervention
5 * Return on the mobile app and clic on sync.
6 * the provisionnal intervention remains on the mobile app

**What is expected**

After being deleted on the web app, the provisionnal intervention must not remains on the mobile app.

**Comment by linuxipho** [comment]
Fixed
