### ISSUE TITLE
No data when the GPS is not able to have a good accuracy

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/zero-android#45]
**Description**

When a user start an intervention on the app and when the GPS accuracy is not sufficient, no point is collected and we haven't got marker on the map.

But if a user deleted the provisionnal intervention on Ekylibre and then the concerned user re-sync the app, the provisionnal intervention remains on the app.

**How to reproduce**

1 * Install the mobile app on your Android phone, use the demo credentials on https://demo.ekylibre.farm (admin@ekylibre.org / 12345678)
2 * Start an intervention in a room.
3 * Clic on the top right of the screen to show the map and no marker is present.

**What is expected**

Having one point at last or alert the user that no point is collected at this place

**Comment by burisu** [comment]
We need to display a message when GPS is too inaccurate. A message should be display below the global chronometer to say if GPS point are taken or not. "GPS fix acquired" when OK and "waiting for GPS fix"
The message should be green if accuracy is good and red if too bad.
